using Metamod.Enum.Common;
using Metamod.Native.Common;
using Metamod.Struct.Common;
using Metamod.Struct.Engine;

namespace Metamod.Interface.Events;

#region Delegates
public delegate int PrecacheModelDelegate(string s);
public delegate int PrecacheSoundDelegate(string s);
public delegate void SetModelDelegate(Edict e, string m);
public delegate int ModelIndexDelegate(string m);
public delegate int ModelFramesDelegate(int modelIndex);
public delegate void SetSizeDelegate(Edict e, Vector3f min, Vector3f max);
public delegate void ChangeLevelDelegate(string s1, string s2);
public delegate void GetSpawnParmsDelegate(Edict ent);
public delegate void SaveSpawnParmsDelegate(Edict ent);
public delegate float VecToYawDelegate(Vector3f vec);
public delegate void VecToAnglesDelegate(Vector3f vec, Vector3f angles);
public delegate void MoveToOriginDelegate(Edict ent, Vector3f goal, float dist, int moveType);
public delegate void ChangeYawDelegate(Edict edict);
public delegate void ChangePitchDelegate(Edict ent);
public delegate Edict FindEntityByStringDelegate(Edict e, string field, string value);
public delegate int GetEntityIllumDelegate(Edict ent);
public delegate Edict FindEntityInSphereDelegate(Edict e, Vector3f origin, float radius);
public delegate Edict FindClientInPVSDelegate(Edict e);
public delegate Edict EntitiesInPVSDelegate(Edict e);
public delegate void MakeVectorsDelegate(Vector3f vec);
public delegate void AngleVectorsDelegate(Vector3f vec, Vector3f forward, Vector3f right, Vector3f up);
public delegate Edict CreateEntityDelegate();
public delegate void RemoveEntityDelegate(Edict e);
public delegate Edict CreateNamedEntityDelegate(int className);
public delegate void MakeStaticDelegate(Edict ent);
public delegate int EntIsOnFloorDelegate(Edict ent);
public delegate int DropToFloorDelegate(Edict ent);
public delegate int WalkMoveDelegate(Edict ent, float yaw, float dist, int mode);
public delegate void SetOriginDelegate(Edict ent, Vector3f origin);
public delegate void EmitSoundDelegate(Edict ent, int channel, string sample, float volume, float attenuation, int fFlags, int pitch);
public delegate void EmitAmbientSoundDelegate(Edict ent, Vector3f pos, string sample, float volume, float attenuation, int fFlags, int pitch);
public delegate void TraceLineDelegate(Vector3f v1, Vector3f v2, int fNoMonsters, Edict pentToSkip, ref TraceResult ptr);
public delegate void TraceTossDelegate(Edict pent, Edict pentToIgnore, ref TraceResult ptr);
public delegate int TraceMonsterHullDelegate(Edict pent, Vector3f v1, Vector3f v2, int fNoMonsters, Edict pentToSkip, ref TraceResult ptr);
public delegate void TraceHullDelegate(Vector3f v1, Vector3f v2, int fNoMonsters, int hullNumber, Edict pentToSkip, ref TraceResult ptr);
public delegate void TraceModelDelegate(Vector3f v1, Vector3f v2, int hullNumber, Edict pent, ref TraceResult ptr);
public delegate string TraceTextureDelegate(Edict pTextureEntity, Vector3f v1, Vector3f v2);
public delegate void TraceSphereDelegate(Vector3f v1, Vector3f v2, int fNoMonsters, float radius, Edict pentToSkip, ref TraceResult ptr);
public delegate void GetAimVectorDelegate(Edict ent, float speed, ref Vector3f vec);
public delegate void ServerCommandDelegate(string str);
public delegate void ServerExecuteDelegate();
public delegate void EngineClientCommandDelegate(Edict ent, string str);
public delegate void ParticleEffectDelegate(Vector3f org, Vector3f dir, float color, float count);
public delegate void LightStyleDelegate(int style, string val);
public delegate int DecalIndexDelegate(string name);
public delegate int PointContentsDelegate(Vector3f vec);
public delegate void MessageBeginDelegate(int msg_dest, int msg_type, Vector3f pOrigin, Edict ed);
public delegate void MessageEndDelegate();
public delegate void WriteByteDelegate(int iValue);
public delegate void WriteCharDelegate(int iValue);
public delegate void WriteShortDelegate(int iValue);
public delegate void WriteLongDelegate(int iValue);
public delegate void WriteAngleDelegate(float flValue);
public delegate void WriteCoordDelegate(float flValue);
public delegate void WriteStringDelegate(string sz);
public delegate void WriteEntityDelegate(int iValue);
public delegate void CVarRegisterDelegate(CVar cvar);
public delegate float CVarGetFloatDelegate(string szVarName);
public delegate string CVarGetStringDelegate(string szVarName);
public delegate void CVarSetFloatDelegate(string szVarName, float flValue);
public delegate void CVarSetStringDelegate(string szVarName, string szValue);
public delegate void AlertMessageDelegate(AlertType atype, string szFmt);
public delegate void EngineFprintfDelegate(nint pFile, string szFmt, params string[] p);
public delegate nint PvAllocEntPrivateDataDelegate(Edict ed, int size);
public delegate nint PvEntPrivateDataDelegate(Edict ed);
public delegate void FreeEntPrivateDataDelegate(Edict ed);
public delegate string SzFromIndexDelegate(int iString);
public delegate int AllocStringDelegate(string szValue);
public delegate Entvars GetVarsOfEntDelegate(Edict pEdict);
public delegate Edict PEntityOfEntOffsetDelegate(int iEntOffset);
public delegate int EntOffsetOfPEntityDelegate(Edict pEdict);
public delegate int IndexOfEdictDelegate(Edict pEdict);
public delegate Edict PEntityOfEntIndexDelegate(int iEntIndex);
public delegate Edict FindEntityByVarsDelegate(Entvars pvars);
public delegate nint GetModelPtrDelegate(Edict pEdict);
public delegate int RegUserMsgDelegate(string pszName, int iSize);
public delegate void AnimationAutomoveDelegate(Edict ent, float flTime);
public delegate void GetBonePositionDelegate(Edict ent, int iBone, ref Vector3f origin, ref Vector3f angles);
public delegate uint FunctionFromNameDelegate(string pName);
public delegate string NameForFunctionDelegate(uint function);
public delegate void ClientPrintfDelegate(Edict ent, PrintType ptype, string szMsg);
public delegate void ServerPrintDelegate(string msg);
public delegate string Cmd_ArgsDelegate();
public delegate string Cmd_ArgvDelegate(int argc);
public delegate int Cmd_ArgcDelegate();
public delegate void GetAttachmentDelegate(Edict ent, int iAttachment, ref Vector3f origin, ref Vector3f angles);
public delegate void CRC32_InitDelegate(CRC32 pulCRC);
public delegate void CRC32_ProcessBufferDelegate(CRC32 pulCRC, nint buffer, int len);
public delegate void CRC32_ProcessByteDelegate(CRC32 pulCRC, byte ch);
public delegate CRC32 CRC32_FinalDelegate(CRC32 pulCRC);
public delegate int RandomLongDelegate(int lLow, int lHigh);
public delegate float RandomFloatDelegate(float flLow, float flHigh);
public delegate void SetViewDelegate(Edict ent, Edict viewent);
public delegate float TimeDelegate();
public delegate void CrosshairAngleDelegate(Edict ent, float pitch, float yaw);
public delegate nint LoadFileForMeDelegate(string filename, out int pLength);
public delegate void FreeFileDelegate(nint buffer);
public delegate void EndSectionDelegate(string szSectionName);
public delegate int CompareFileTimeDelegate(string filename1, string filename2, out int iCompare);
public delegate string GetGameDirDelegate();
public delegate void CVar_RegisterVariableDelegate(CVar cvar);
public delegate void FadeClientVolumeDelegate(Edict ent, int fadePercent, int fadeOutSeconds, int holdTime, int fadeInSeconds);
public delegate void SetClientMaxspeedDelegate(Edict ent, float fNewMaxspeed);
public delegate Edict CreateFakeClientDelegate(string netname);
public delegate void RunPlayerMoveDelegate(Edict fakeClient, Vector3f viewangles, float forwardmove, float sidemove, float upmove, ushort buttons, byte impulse, byte msec);
public delegate int NumberOfEntitiesDelegate();
public delegate string GetInfoKeyBufferDelegate(Edict ent);
public delegate string InfoKeyValueDelegate(string infobuffer, string key);
public delegate void SetKeyValueDelegate(ref string infobuffer, string key, string value);
public delegate void SetClientKeyValueDelegate(int clientIndex, string infobuffer, string key, string value);
public delegate bool IsMapValidDelegate(string filename);
public delegate void StaticDecalDelegate(Vector3f origin, int decalIndex, int entityIndex, int modelIndex);
public delegate int PrecacheGenericDelegate(string s);
public delegate int GetPlayerUserIdDelegate(Edict e);
public delegate void BuildSoundMsgDelegate(Edict entity, int channel, string sample, float volume, float attenuation, int fFlags, int pitch, int msg_dest, int msg_type, Vector3f pOrigin, Edict ed);
public delegate bool IsDedicatedServerDelegate();
public delegate CVar CVarGetPointerDelegate(string szVarName);
public delegate uint GetPlayerWONIdDelegate(Edict e);
public delegate void Info_RemoveKeyDelegate(ref string s, string key);
public delegate string GetPhysicsKeyValueDelegate(Edict ent, string key);
public delegate void SetPhysicsKeyValueDelegate(Edict ent, string key, string value);
public delegate string GetPhysicsInfoStringDelegate(Edict ent);
public delegate ushort PrecacheEventDelegate(int type, string psz);
public delegate void PlaybackEventDelegate(int flags, Edict ed, ushort eventindex, float delay, Vector3f origin, Vector3f angles, float fparam1, float fparam2, int iparam1, int iparam2, int bparam1, int bparam2);
public delegate string SetFatPVSDelegate(Vector3f org);
public delegate string SetFatPASDelegate(Vector3f org);
public delegate bool CheckVisibilityDelegate(Edict entity, nint pset);
public delegate void DeltaSetFieldDelegate(nint pFields, string fieldName);
public delegate void DeltaUnsetFieldDelegate(nint pFields, string fieldName);
public delegate void DeltaAddEncoderDelegate(string name, nint callback);
public delegate int GetCurrentPlayerDelegate();
public delegate int CanSkipPlayerDelegate(Edict player);
public delegate int DeltaFindFieldDelegate(nint pFields, string fieldName);
public delegate void DeltaSetFieldByIndexDelegate(nint pFields, int fieldNumber);
public delegate void DeltaUnsetFieldByIndexDelegate(nint pFields, int fieldNumber);
public delegate void SetGroupMaskDelegate(int mask, int op);
public delegate int CreateInstancedBaselineDelegate(int classname, EntityState baseline);
public delegate void Cvar_DirectSetDelegate(CVar cvar, string value);
public delegate void ForceUnmodifiedDelegate(ForceType type, Vector3f mins, Vector3f maxs, string filename);
public delegate void GetPlayerStatsDelegate(Edict ent, out int ping, out int packet_loss);
public delegate void AddServerCommandDelegate(string cmd_name, ServerCommandDelegate function);
public delegate bool Voice_GetClientListeningDelegate(int iReceiver, int iSender);
public delegate bool Voice_SetClientListeningDelegate(int iReceiver, int iSender, bool bListen);
public delegate string GetPlayerAuthIdDelegate(Edict e);
public delegate nint SequenceGetDelegate(string fieldName, string entryName);
public delegate nint SequencePickSentenceDelegate(string groupName, int pickMethod, out int picked);
public delegate int GetFileSizeDelegate(string filename);
public delegate uint GetApproxWavePlayLenDelegate(string filepath);
public delegate int IsCareerMatchDelegate();
public delegate int GetLocalizedStringLengthDelegate(string label);
public delegate void RegisterTutorMessageShownDelegate(int mid);
public delegate int GetTimesTutorMessageShownDelegate(int mid);
public delegate void ProcessTutorMessageDecayBufferDelegate(nint buffer, int bufferLength);
public delegate void ConstructTutorMessageDecayBufferDelegate(nint buffer, int bufferLength);
public delegate void ResetTutorMessageDecayDataDelegate();
public delegate void QueryClientCvarValueDelegate(Edict player, string cvarName);
public delegate void QueryClientCvarValue2Delegate(Edict player, string cvarName, int requestID);
public delegate int EngCheckParmDelegate(string pchCmdLineToken, out string ppszValue);
#endregion


public class EngineEvents
{
    #region Events
    public event PrecacheModelDelegate? PrecacheModel;
    public event PrecacheSoundDelegate? PrecacheSound;
    public event SetModelDelegate? SetModel;
    public event ModelIndexDelegate? ModelIndex;
    public event ModelFramesDelegate? ModelFrames;
    public event SetSizeDelegate? SetSize;
    public event ChangeLevelDelegate? ChangeLevel;
    public event GetSpawnParmsDelegate? GetSpawnParms;
    public event SaveSpawnParmsDelegate? SaveSpawnParms;
    public event VecToYawDelegate? VecToYaw;
    public event VecToAnglesDelegate? VecToAngles;
    public event MoveToOriginDelegate? MoveToOrigin;
    public event ChangeYawDelegate? ChangeYaw;
    public event ChangePitchDelegate? ChangePitch;
    public event FindEntityByStringDelegate? FindEntityByString;
    public event GetEntityIllumDelegate? GetEntityIllum;
    public event FindEntityInSphereDelegate? FindEntityInSphere;
    public event FindClientInPVSDelegate? FindClientInPVS;
    public event EntitiesInPVSDelegate? EntitiesInPVS;
    public event MakeVectorsDelegate? MakeVectors;
    public event AngleVectorsDelegate? AngleVectors;
    public event CreateEntityDelegate? CreateEntity;
    public event RemoveEntityDelegate? RemoveEntity;
    public event CreateNamedEntityDelegate? CreateNamedEntity;
    public event MakeStaticDelegate? MakeStatic;
    public event EntIsOnFloorDelegate? EntIsOnFloor;
    public event DropToFloorDelegate? DropToFloor;
    public event WalkMoveDelegate? WalkMove;
    public event SetOriginDelegate? SetOrigin;
    public event EmitSoundDelegate? EmitSound;
    public event EmitAmbientSoundDelegate? EmitAmbientSound;
    public event TraceLineDelegate? TraceLine;
    public event TraceTossDelegate? TraceToss;
    public event TraceMonsterHullDelegate? TraceMonsterHull;
    public event TraceHullDelegate? TraceHull;
    public event TraceModelDelegate? TraceModel;
    public event TraceTextureDelegate? TraceTexture;
    public event TraceSphereDelegate? TraceSphere;
    public event GetAimVectorDelegate? GetAimVector;
    public event ServerCommandDelegate? ServerCommand;
    public event ServerExecuteDelegate? ServerExecute;
    public event EngineClientCommandDelegate? ClientCommand;
    public event ParticleEffectDelegate? ParticleEffect;
    public event LightStyleDelegate? LightStyle;
    public event DecalIndexDelegate? DecalIndex;
    public event PointContentsDelegate? PointContents;
    public event MessageBeginDelegate? MessageBegin;
    public event MessageEndDelegate? MessageEnd;
    public event WriteByteDelegate? WriteByte;
    public event WriteCharDelegate? WriteChar;
    public event WriteShortDelegate? WriteShort;
    public event WriteLongDelegate? WriteLong;
    public event WriteAngleDelegate? WriteAngle;
    public event WriteCoordDelegate? WriteCoord;
    public event WriteStringDelegate? WriteString;
    public event WriteEntityDelegate? WriteEntity;
    public event CVarRegisterDelegate? CVarRegister;
    public event CVarGetFloatDelegate? CVarGetFloat;
    public event CVarGetStringDelegate? CVarGetString;
    public event CVarSetFloatDelegate? CVarSetFloat;
    public event CVarSetStringDelegate? CVarSetString;
    public event AlertMessageDelegate? AlertMessage;
    public event EngineFprintfDelegate? EngineFprintf;
    public event PvAllocEntPrivateDataDelegate? PvAllocEntPrivateData;
    public event PvEntPrivateDataDelegate? PvEntPrivateData;
    public event FreeEntPrivateDataDelegate? FreeEntPrivateData;
    public event SzFromIndexDelegate? SzFromIndex;
    public event AllocStringDelegate? AllocString;
    public event GetVarsOfEntDelegate? GetVarsOfEnt;
    public event PEntityOfEntOffsetDelegate? PEntityOfEntOffset;
    public event EntOffsetOfPEntityDelegate? EntOffsetOfPEntity;
    public event IndexOfEdictDelegate? IndexOfEdict;
    public event PEntityOfEntIndexDelegate? PEntityOfEntIndex;
    public event FindEntityByVarsDelegate? FindEntityByVars;
    public event GetModelPtrDelegate? GetModelPtr;
    public event RegUserMsgDelegate? RegUserMsg;
    public event AnimationAutomoveDelegate? AnimationAutomove;
    public event GetBonePositionDelegate? GetBonePosition;
    public event FunctionFromNameDelegate? FunctionFromName;
    public event NameForFunctionDelegate? NameForFunction;
    public event ClientPrintfDelegate? ClientPrintf;
    public event ServerPrintDelegate? ServerPrint;
    public event Cmd_ArgsDelegate? Cmd_Args;
    public event Cmd_ArgvDelegate? Cmd_Argv;
    public event Cmd_ArgcDelegate? Cmd_Argc;
    public event GetAttachmentDelegate? GetAttachment;
    public event CRC32_InitDelegate? CRC32_Init;
    public event CRC32_ProcessBufferDelegate? CRC32_ProcessBuffer;
    public event CRC32_ProcessByteDelegate? CRC32_ProcessByte;
    public event CRC32_FinalDelegate? CRC32_Final;
    public event RandomLongDelegate? RandomLong;
    public event RandomFloatDelegate? RandomFloat;
    public event SetViewDelegate? SetView;
    public event TimeDelegate? Time;
    public event CrosshairAngleDelegate? CrosshairAngle;
    public event LoadFileForMeDelegate? LoadFileForMe;
    public event FreeFileDelegate? FreeFile;
    public event EndSectionDelegate? EndSection;
    public event CompareFileTimeDelegate? CompareFileTime;
    public event GetGameDirDelegate? GetGameDir;
    public event CVar_RegisterVariableDelegate? Cvar_RegisterVariable;
    public event FadeClientVolumeDelegate? FadeClientVolume;
    public event SetClientMaxspeedDelegate? SetClientMaxspeed;
    public event CreateFakeClientDelegate? CreateFakeClient;
    public event RunPlayerMoveDelegate? RunPlayerMove;
    public event NumberOfEntitiesDelegate? NumberOfEntities;
    public event GetInfoKeyBufferDelegate? GetInfoKeyBuffer;
    public event InfoKeyValueDelegate? InfoKeyValue;
    public event SetKeyValueDelegate? SetKeyValue;
    public event SetClientKeyValueDelegate? SetClientKeyValue;
    public event IsMapValidDelegate? IsMapValid;
    public event StaticDecalDelegate? StaticDecal;
    public event PrecacheGenericDelegate? PrecacheGeneric;
    public event GetPlayerUserIdDelegate? GetPlayerUserId;
    public event BuildSoundMsgDelegate? BuildSoundMsg;
    public event IsDedicatedServerDelegate? IsDedicatedServer;
    public event CVarGetPointerDelegate? CVarGetPointer;
    public event GetPlayerWONIdDelegate? GetPlayerWONId;
    public event Info_RemoveKeyDelegate? Info_RemoveKey;
    public event GetPhysicsKeyValueDelegate? GetPhysicsKeyValue;
    public event SetPhysicsKeyValueDelegate? SetPhysicsKeyValue;
    public event GetPhysicsInfoStringDelegate? GetPhysicsInfoString;
    public event PrecacheEventDelegate? PrecacheEvent;
    public event PlaybackEventDelegate? PlaybackEvent;
    public event SetFatPVSDelegate? SetFatPVS;
    public event SetFatPASDelegate? SetFatPAS;
    public event CheckVisibilityDelegate? CheckVisibility;
    public event DeltaSetFieldDelegate? DeltaSetField;
    public event DeltaUnsetFieldDelegate? DeltaUnsetField;
    public event DeltaAddEncoderDelegate? DeltaAddEncoder;
    public event GetCurrentPlayerDelegate? GetCurrentPlayer;
    public event CanSkipPlayerDelegate? CanSkipPlayer;
    public event DeltaFindFieldDelegate? DeltaFindField;
    public event DeltaSetFieldByIndexDelegate? DeltaSetFieldByIndex;
    public event DeltaUnsetFieldByIndexDelegate? DeltaUnsetFieldByIndex;
    public event SetGroupMaskDelegate? SetGroupMask;
    public event CreateInstancedBaselineDelegate? CreateInstancedBaseline;
    public event Cvar_DirectSetDelegate? Cvar_DirectSet;
    public event ForceUnmodifiedDelegate? ForceUnmodified;
    public event GetPlayerStatsDelegate? GetPlayerStats;
    public event AddServerCommandDelegate? AddServerCommand;
    public event Voice_GetClientListeningDelegate? Voice_GetClientListening;
    public event Voice_SetClientListeningDelegate? Voice_SetClientListening;
    public event GetPlayerAuthIdDelegate? GetPlayerAuthId;
    public event SequenceGetDelegate? SequenceGet;
    public event SequencePickSentenceDelegate? SequencePickSentence;
    public event GetFileSizeDelegate? GetFileSize;
    public event GetApproxWavePlayLenDelegate? GetApproxWavePlayLen;
    public event IsCareerMatchDelegate? IsCareerMatch;
    public event GetLocalizedStringLengthDelegate? GetLocalizedStringLength;
    public event RegisterTutorMessageShownDelegate? RegisterTutorMessageShown;
    public event GetTimesTutorMessageShownDelegate? GetTimesTutorMessageShown;
    public event ProcessTutorMessageDecayBufferDelegate? ProcessTutorMessageDecayBuffer;
    public event ConstructTutorMessageDecayBufferDelegate? ConstructTutorMessageDecayBuffer;
    public event ResetTutorMessageDecayDataDelegate? ResetTutorMessageDecayData;
    public event QueryClientCvarValueDelegate? QueryClientCvarValue;
    public event QueryClientCvarValue2Delegate? QueryClientCvarValue2;
    public event EngCheckParmDelegate? EngCheckParm;
    #endregion

    #region Invoker
    internal int InvokePrecacheModel(string s) => PrecacheModel?.Invoke(s) ?? 0;
    internal int InvokePrecacheSound(string s) => PrecacheSound?.Invoke(s) ?? 0;
    internal void InvokeSetModel(Edict e, string m) => SetModel?.Invoke(e, m);
    internal int InvokeModelIndex(string m) => ModelIndex != null ? ModelIndex.Invoke(m) : 0;
    internal int InvokeModelFrames(int modelIndex) => ModelFrames != null ? ModelFrames.Invoke(modelIndex) : 0;
    internal void InvokeSetSize(Edict e, Vector3f min, Vector3f max) => SetSize?.Invoke(e, min, max);
    internal void InvokeChangeLevel(string s1, string s2) => ChangeLevel?.Invoke(s1, s2);
    internal void InvokeGetSpawnParms(Edict ent) => GetSpawnParms?.Invoke(ent);
    internal void InvokeSaveSpawnParms(Edict ent) => SaveSpawnParms?.Invoke(ent);
    internal float InvokeVecToYaw(Vector3f vec) => VecToYaw != null ? VecToYaw.Invoke(vec) : 0f;
    internal void InvokeVecToAngles(Vector3f vec, Vector3f angles) => VecToAngles?.Invoke(vec, angles);
    internal void InvokeMoveToOrigin(Edict ent, Vector3f goal, float dist, int moveType) => MoveToOrigin?.Invoke(ent, goal, dist, moveType);
    internal void InvokeChangeYaw(Edict edict) => ChangeYaw?.Invoke(edict);
    internal void InvokeChangePitch(Edict ent) => ChangePitch?.Invoke(ent);
    internal Edict InvokeFindEntityByString(Edict e, string field, string value) => FindEntityByString != null ? FindEntityByString.Invoke(e, field, value) : new Edict();
    internal int InvokeGetEntityIllum(Edict ent) => GetEntityIllum != null ? GetEntityIllum.Invoke(ent) : 0;
    internal Edict InvokeFindEntityInSphere(Edict e, Vector3f origin, float radius) => FindEntityInSphere != null ? FindEntityInSphere.Invoke(e, origin, radius) : new Edict();
    internal Edict InvokeFindClientInPVS(Edict e) => FindClientInPVS != null ? FindClientInPVS.Invoke(e) : new Edict();
    internal Edict InvokeEntitiesInPVS(Edict e) => EntitiesInPVS != null ? EntitiesInPVS.Invoke(e) : new Edict();
    internal void InvokeMakeVectors(Vector3f vec) => MakeVectors?.Invoke(vec);
    internal void InvokeAngleVectors(Vector3f vec, Vector3f forward, Vector3f right, Vector3f up) => AngleVectors?.Invoke(vec, forward, right, up);
    internal Edict InvokeCreateEntity() => CreateEntity != null ? CreateEntity.Invoke() : new Edict();
    internal void InvokeRemoveEntity(Edict e) => RemoveEntity?.Invoke(e);
    internal Edict InvokeCreateNamedEntity(int className) => CreateNamedEntity != null ? CreateNamedEntity.Invoke(className) : new Edict();
    internal void InvokeMakeStatic(Edict ent) => MakeStatic?.Invoke(ent);
    internal int InvokeEntIsOnFloor(Edict ent) => EntIsOnFloor != null ? EntIsOnFloor.Invoke(ent) : 0;
    internal int InvokeDropToFloor(Edict ent) => DropToFloor != null ? DropToFloor.Invoke(ent) : 0;
    internal int InvokeWalkMove(Edict ent, float yaw, float dist, int mode) => WalkMove != null ? WalkMove.Invoke(ent, yaw, dist, mode) : 0;
    internal void InvokeSetOrigin(Edict ent, Vector3f origin) => SetOrigin?.Invoke(ent, origin);
    internal void InvokeEmitSound(Edict ent, int channel, string sample, float volume, float attenuation, int fFlags, int pitch) => EmitSound?.Invoke(ent, channel, sample, volume, attenuation, fFlags, pitch);
    internal void InvokeEmitAmbientSound(Edict ent, Vector3f pos, string sample, float volume, float attenuation, int fFlags, int pitch) => EmitAmbientSound?.Invoke(ent, pos, sample, volume, attenuation, fFlags, pitch);
    internal void InvokeTraceLine(Vector3f v1, Vector3f v2, int fNoMonsters, Edict pentToSkip, ref TraceResult ptr) => TraceLine?.Invoke(v1, v2, fNoMonsters, pentToSkip, ref ptr);
    internal void InvokeTraceToss(Edict pent, Edict pentToIgnore, ref TraceResult ptr) => TraceToss?.Invoke(pent, pentToIgnore, ref ptr);
    internal int InvokeTraceMonsterHull(Edict pent, Vector3f v1, Vector3f v2, int fNoMonsters, Edict pentToSkip, ref TraceResult ptr) => TraceMonsterHull != null ? TraceMonsterHull.Invoke(pent, v1, v2, fNoMonsters, pentToSkip, ref ptr) : 0;
    internal void InvokeTraceHull(Vector3f v1, Vector3f v2, int fNoMonsters, int hullNumber, Edict pentToSkip, ref TraceResult ptr) => TraceHull?.Invoke(v1, v2, fNoMonsters, hullNumber, pentToSkip, ref ptr);
    internal void InvokeTraceModel(Vector3f v1, Vector3f v2, int hullNumber, Edict pent, ref TraceResult ptr) => TraceModel?.Invoke(v1, v2, hullNumber, pent, ref ptr);
    internal string InvokeTraceTexture(Edict pTextureEntity, Vector3f v1, Vector3f v2) => TraceTexture != null ? TraceTexture.Invoke(pTextureEntity, v1, v2) : string.Empty;
    internal void InvokeTraceSphere(Vector3f v1, Vector3f v2, int fNoMonsters, float radius, Edict pentToSkip, ref TraceResult ptr) => TraceSphere?.Invoke(v1, v2, fNoMonsters, radius, pentToSkip, ref ptr);
    internal void InvokeGetAimVector(Edict ent, float speed, ref Vector3f vec) => GetAimVector?.Invoke(ent, speed, ref vec);
    internal void InvokeServerCommand(string str) => ServerCommand?.Invoke(str);
    internal void InvokeServerExecute() => ServerExecute?.Invoke();
    internal void InvokeClientCommand(Edict ent, string str) => ClientCommand?.Invoke(ent, str);
    internal void InvokeParticleEffect(Vector3f org, Vector3f dir, float color, float count) => ParticleEffect?.Invoke(org, dir, color, count);
    internal void InvokeLightStyle(int style, string val) => LightStyle?.Invoke(style, val);
    internal int InvokeDecalIndex(string name) => DecalIndex != null ? DecalIndex.Invoke(name) : 0;
    internal int InvokePointContents(Vector3f vec) => PointContents != null ? PointContents.Invoke(vec) : 0;
    internal void InvokeMessageBegin(int msg_dest, int msg_type, Vector3f pOrigin, Edict ed) => MessageBegin?.Invoke(msg_dest, msg_type, pOrigin, ed);
    internal void InvokeMessageEnd() => MessageEnd?.Invoke();
    internal void InvokeWriteByte(int iValue) => WriteByte?.Invoke(iValue);
    internal void InvokeWriteChar(int iValue) => WriteChar?.Invoke(iValue);
    internal void InvokeWriteShort(int iValue) => WriteShort?.Invoke(iValue);
    internal void InvokeWriteLong(int iValue) => WriteLong?.Invoke(iValue);
    internal void InvokeWriteAngle(float flValue) => WriteAngle?.Invoke(flValue);
    internal void InvokeWriteCoord(float flValue) => WriteCoord?.Invoke(flValue);
    internal void InvokeWriteString(string sz) => WriteString?.Invoke(sz);
    internal void InvokeWriteEntity(int iValue) => WriteEntity?.Invoke(iValue);
    internal void InvokeCVarRegister(CVar cvar) => CVarRegister?.Invoke(cvar);
    internal float InvokeCVarGetFloat(string szVarName) => CVarGetFloat != null ? CVarGetFloat.Invoke(szVarName) : 0f;
    internal string InvokeCVarGetString(string szVarName) => CVarGetString != null ? CVarGetString.Invoke(szVarName) : string.Empty;
    internal void InvokeCVarSetFloat(string szVarName, float flValue) => CVarSetFloat?.Invoke(szVarName, flValue);
    internal void InvokeCVarSetString(string szVarName, string szValue) => CVarSetString?.Invoke(szVarName, szValue);
    internal void InvokeAlertMessage(AlertType atype, string szFmt) => AlertMessage?.Invoke(atype, szFmt);
    internal void InvokeEngineFprintf(nint pFile, string szFmt, params string[] p) => EngineFprintf?.Invoke(pFile, szFmt, p);
    internal nint InvokePvAllocEntPrivateData(Edict ed, int size) => PvAllocEntPrivateData != null ? PvAllocEntPrivateData.Invoke(ed, size) : nint.Zero;
    internal nint InvokePvEntPrivateData(Edict ed) => PvEntPrivateData != null ? PvEntPrivateData.Invoke(ed) : nint.Zero;
    internal void InvokeFreeEntPrivateData(Edict ed) => FreeEntPrivateData?.Invoke(ed);
    internal string InvokeSzFromIndex(int iString) => SzFromIndex != null ? SzFromIndex.Invoke(iString) : string.Empty;
    internal int InvokeAllocString(string szValue) => AllocString != null ? AllocString.Invoke(szValue) : 0;
    internal Entvars InvokeGetVarsOfEnt(Edict pEdict) => GetVarsOfEnt != null ? GetVarsOfEnt.Invoke(pEdict) : new Entvars();
    internal Edict InvokePEntityOfEntOffset(int iEntOffset) => PEntityOfEntOffset != null ? PEntityOfEntOffset.Invoke(iEntOffset) : new Edict();
    internal int InvokeEntOffsetOfPEntity(Edict pEdict) => EntOffsetOfPEntity != null ? EntOffsetOfPEntity.Invoke(pEdict) : 0;
    internal int InvokeIndexOfEdict(Edict pEdict) => IndexOfEdict != null ? IndexOfEdict.Invoke(pEdict) : 0;
    internal Edict InvokePEntityOfEntIndex(int iEntIndex) => PEntityOfEntIndex != null ? PEntityOfEntIndex.Invoke(iEntIndex) : new Edict();
    internal Edict InvokeFindEntityByVars(Entvars pvars) => FindEntityByVars != null ? FindEntityByVars.Invoke(pvars) : new Edict();
    internal nint InvokeGetModelPtr(Edict pEdict) => GetModelPtr != null ? GetModelPtr.Invoke(pEdict) : nint.Zero;
    internal int InvokeRegUserMsg(string pszName, int iSize) => RegUserMsg != null ? RegUserMsg.Invoke(pszName, iSize) : 0;
    internal void InvokeAnimationAutomove(Edict ent, float flTime) => AnimationAutomove?.Invoke(ent, flTime);
    internal void InvokeGetBonePosition(Edict ent, int iBone, ref Vector3f origin, ref Vector3f angles) => GetBonePosition?.Invoke(ent, iBone, ref origin, ref angles);
    internal uint InvokeFunctionFromName(string pName) => FunctionFromName != null ? FunctionFromName.Invoke(pName) : 0u;
    internal string InvokeNameForFunction(uint function) => NameForFunction != null ? NameForFunction.Invoke(function) : string.Empty;
    internal void InvokeClientPrintf(Edict ent, PrintType ptype, string szMsg) => ClientPrintf?.Invoke(ent, ptype, szMsg);
    internal void InvokeServerPrint(string msg) => ServerPrint?.Invoke(msg);
    internal string InvokeCmd_Args() => Cmd_Args != null ? Cmd_Args.Invoke() : string.Empty;
    internal string InvokeCmd_Argv(int argc) => Cmd_Argv != null ? Cmd_Argv.Invoke(argc) : string.Empty;
    internal int InvokeCmd_Argc() => Cmd_Argc != null ? Cmd_Argc.Invoke() : 0;
    internal void InvokeGetAttachment(Edict ent, int iAttachment, ref Vector3f origin, ref Vector3f angles) => GetAttachment?.Invoke(ent, iAttachment, ref origin, ref angles);
    internal void InvokeCRC32_Init(CRC32 pulCRC) => CRC32_Init?.Invoke(pulCRC);
    internal void InvokeCRC32_ProcessBuffer(CRC32 pulCRC, nint buffer, int len) => CRC32_ProcessBuffer?.Invoke(pulCRC, buffer, len);
    internal void InvokeCRC32_ProcessByte(CRC32 pulCRC, byte ch) => CRC32_ProcessByte?.Invoke(pulCRC, ch);
    internal CRC32 InvokeCRC32_Final(CRC32 pulCRC) => CRC32_Final != null ? CRC32_Final.Invoke(pulCRC) : new CRC32(new NativeCRC32());
    internal int InvokeRandomLong(int lLow, int lHigh) => RandomLong != null ? RandomLong.Invoke(lLow, lHigh) : 0;
    internal float InvokeRandomFloat(float flLow, float flHigh) => RandomFloat != null ? RandomFloat.Invoke(flLow, flHigh) : 0f;
    internal void InvokeSetView(Edict ent, Edict viewent) => SetView?.Invoke(ent, viewent);
    internal float InvokeTime() => Time != null ? Time.Invoke() : 0f;
    internal void InvokeCrosshairAngle(Edict ent, float pitch, float yaw) => CrosshairAngle?.Invoke(ent, pitch, yaw);
    internal nint InvokeLoadFileForMe(string filename, out int pLength) { if (LoadFileForMe != null) return LoadFileForMe.Invoke(filename, out pLength); pLength = 0; return nint.Zero; }
    internal void InvokeFreeFile(nint buffer) => FreeFile?.Invoke(buffer);
    internal void InvokeEndSection(string szSectionName) => EndSection?.Invoke(szSectionName);
    internal int InvokeCompareFileTime(string filename1, string filename2, out int iCompare) { if (CompareFileTime != null) return CompareFileTime.Invoke(filename1, filename2, out iCompare); iCompare = 0; return 0; }
    internal string InvokeGetGameDir() => GetGameDir != null ? GetGameDir.Invoke() : string.Empty;
    internal void InvokeCVar_RegisterVariable(CVar cvar) => Cvar_RegisterVariable?.Invoke(cvar);
    internal void InvokeFadeClientVolume(Edict ent, int fadePercent, int fadeOutSeconds, int holdTime, int fadeInSeconds) => FadeClientVolume?.Invoke(ent, fadePercent, fadeOutSeconds, holdTime, fadeInSeconds);
    internal void InvokeSetClientMaxspeed(Edict ent, float fNewMaxspeed) => SetClientMaxspeed?.Invoke(ent, fNewMaxspeed);
    internal Edict InvokeCreateFakeClient(string netname) => CreateFakeClient != null ? CreateFakeClient.Invoke(netname) : new Edict();
    internal void InvokeRunPlayerMove(Edict fakeClient, Vector3f viewangles, float forwardmove, float sidemove, float upmove, ushort buttons, byte impulse, byte msec) => RunPlayerMove?.Invoke(fakeClient, viewangles, forwardmove, sidemove, upmove, buttons, impulse, msec);
    internal int InvokeNumberOfEntities() => NumberOfEntities != null ? NumberOfEntities.Invoke() : 0;
    internal string InvokeGetInfoKeyBuffer(Edict ent) => GetInfoKeyBuffer != null ? GetInfoKeyBuffer.Invoke(ent) : string.Empty;
    internal string InvokeInfoKeyValue(string infobuffer, string key) => InfoKeyValue != null ? InfoKeyValue.Invoke(infobuffer, key) : string.Empty;
    internal void InvokeSetKeyValue(ref string infobuffer, string key, string value) => SetKeyValue?.Invoke(ref infobuffer, key, value);
    internal void InvokeSetClientKeyValue(int clientIndex, string infobuffer, string key, string value) => SetClientKeyValue?.Invoke(clientIndex, infobuffer, key, value);
    internal bool InvokeIsMapValid(string filename) => IsMapValid != null ? IsMapValid.Invoke(filename) : false;
    internal void InvokeStaticDecal(Vector3f origin, int decalIndex, int entityIndex, int modelIndex) => StaticDecal?.Invoke(origin, decalIndex, entityIndex, modelIndex);
    internal int InvokePrecacheGeneric(string s) => PrecacheGeneric?.Invoke(s) ?? 0;
    internal int InvokeGetPlayerUserId(Edict e) => GetPlayerUserId != null ? GetPlayerUserId.Invoke(e) : 0;
    internal void InvokeBuildSoundMsg(Edict entity, int channel, string sample, float volume, float attenuation, int fFlags, int pitch, int msg_dest, int msg_type, Vector3f pOrigin, Edict ed) => BuildSoundMsg?.Invoke(entity, channel, sample, volume, attenuation, fFlags, pitch, msg_dest, msg_type, pOrigin, ed);
    internal bool InvokeIsDedicatedServer() => IsDedicatedServer != null ? IsDedicatedServer.Invoke() : false;
    internal CVar InvokeCVarGetPointer(string szVarName) => CVarGetPointer != null ? CVarGetPointer.Invoke(szVarName) : new CVar();
    internal uint InvokeGetPlayerWONId(Edict e) => GetPlayerWONId != null ? GetPlayerWONId.Invoke(e) : 0u;
    internal void InvokeInfo_RemoveKey(ref string s, string key) => Info_RemoveKey?.Invoke(ref s, key);
    internal string InvokeGetPhysicsKeyValue(Edict ent, string key) => GetPhysicsKeyValue != null ? GetPhysicsKeyValue.Invoke(ent, key) : string.Empty;
    internal void InvokeSetPhysicsKeyValue(Edict ent, string key, string value) => SetPhysicsKeyValue?.Invoke(ent, key, value);
    internal string InvokeGetPhysicsInfoString(Edict ent) => GetPhysicsInfoString != null ? GetPhysicsInfoString.Invoke(ent) : string.Empty;
    internal ushort InvokePrecacheEvent(int type, string psz) => PrecacheEvent != null ? PrecacheEvent.Invoke(type, psz) : (ushort)0;
    internal void InvokePlaybackEvent(int flags, Edict ed, ushort eventindex, float delay, Vector3f origin, Vector3f angles, float fparam1, float fparam2, int iparam1, int iparam2, int bparam1, int bparam2) => PlaybackEvent?.Invoke(flags, ed, eventindex, delay, origin, angles, fparam1, fparam2, iparam1, iparam2, bparam1, bparam2);
    internal string InvokeSetFatPVS(Vector3f org) => SetFatPVS != null ? SetFatPVS.Invoke(org) : string.Empty;
    internal string InvokeSetFatPAS(Vector3f org) => SetFatPAS != null ? SetFatPAS.Invoke(org) : string.Empty;
    internal bool InvokeCheckVisibility(Edict entity, nint pset) => CheckVisibility != null ? CheckVisibility.Invoke(entity, pset) : false;
    internal void InvokeDeltaSetField(nint pFields, string fieldName) => DeltaSetField?.Invoke(pFields, fieldName);
    internal void InvokeDeltaUnsetField(nint pFields, string fieldName) => DeltaUnsetField?.Invoke(pFields, fieldName);
    internal void InvokeDeltaAddEncoder(string name, nint callback) => DeltaAddEncoder?.Invoke(name, callback);
    internal int InvokeGetCurrentPlayer() => GetCurrentPlayer != null ? GetCurrentPlayer.Invoke() : 0;
    internal int InvokeCanSkipPlayer(Edict player) => CanSkipPlayer != null ? CanSkipPlayer.Invoke(player) : 0;
    internal int InvokeDeltaFindField(nint pFields, string fieldName) => DeltaFindField != null ? DeltaFindField.Invoke(pFields, fieldName) : 0;
    internal void InvokeDeltaSetFieldByIndex(nint pFields, int fieldNumber) => DeltaSetFieldByIndex?.Invoke(pFields, fieldNumber);
    internal void InvokeDeltaUnsetFieldByIndex(nint pFields, int fieldNumber) => DeltaUnsetFieldByIndex?.Invoke(pFields, fieldNumber);
    internal void InvokeSetGroupMask(int mask, int op) => SetGroupMask?.Invoke(mask, op);
    internal int InvokeCreateInstancedBaseline(int classname, EntityState baseline) => CreateInstancedBaseline != null ? CreateInstancedBaseline.Invoke(classname, baseline) : 0;
    internal void InvokeCvar_DirectSet(CVar cvar, string value) => Cvar_DirectSet?.Invoke(cvar, value);
    internal void InvokeForceUnmodified(ForceType type, Vector3f mins, Vector3f maxs, string filename) => ForceUnmodified?.Invoke(type, mins, maxs, filename);
    internal void InvokeGetPlayerStats(Edict ent, out int ping, out int packet_loss) { if (GetPlayerStats != null) { GetPlayerStats.Invoke(ent, out ping, out packet_loss); } else { ping = 0; packet_loss = 0; } }
    internal void InvokeAddServerCommand(string cmd_name, ServerCommandDelegate function) => AddServerCommand?.Invoke(cmd_name, function);
    internal bool InvokeVoice_GetClientListening(int iReceiver, int iSender) => Voice_GetClientListening != null ? Voice_GetClientListening.Invoke(iReceiver, iSender) : false;
    internal bool InvokeVoice_SetClientListening(int iReceiver, int iSender, bool bListen) => Voice_SetClientListening != null ? Voice_SetClientListening.Invoke(iReceiver, iSender, bListen) : false;
    internal string InvokeGetPlayerAuthId(Edict e) => GetPlayerAuthId != null ? GetPlayerAuthId.Invoke(e) : string.Empty;
    internal nint InvokeSequenceGet(string fieldName, string entryName) => SequenceGet != null ? SequenceGet.Invoke(fieldName, entryName) : nint.Zero;
    internal nint InvokeSequencePickSentence(string groupName, int pickMethod, out int picked) { if (SequencePickSentence != null) return SequencePickSentence.Invoke(groupName, pickMethod, out picked); picked = 0; return nint.Zero; }
    internal int InvokeGetFileSize(string filename) => GetFileSize != null ? GetFileSize.Invoke(filename) : 0;
    internal uint InvokeGetApproxWavePlayLen(string filepath) => GetApproxWavePlayLen != null ? GetApproxWavePlayLen.Invoke(filepath) : 0u;
    internal int InvokeIsCareerMatch() => IsCareerMatch != null ? IsCareerMatch.Invoke() : 0;
    internal int InvokeGetLocalizedStringLength(string label) => GetLocalizedStringLength != null ? GetLocalizedStringLength.Invoke(label) : 0;
    internal void InvokeRegisterTutorMessageShown(int mid) => RegisterTutorMessageShown?.Invoke(mid);
    internal int InvokeGetTimesTutorMessageShown(int mid) => GetTimesTutorMessageShown != null ? GetTimesTutorMessageShown.Invoke(mid) : 0;
    internal void InvokeProcessTutorMessageDecayBuffer(nint buffer, int bufferLength) => ProcessTutorMessageDecayBuffer?.Invoke(buffer, bufferLength);
    internal void InvokeConstructTutorMessageDecayBuffer(nint buffer, int bufferLength) => ConstructTutorMessageDecayBuffer?.Invoke(buffer, bufferLength);
    internal void InvokeResetTutorMessageDecayData() => ResetTutorMessageDecayData?.Invoke();
    internal void InvokeQueryClientCvarValue(Edict player, string cvarName) => QueryClientCvarValue?.Invoke(player, cvarName);
    internal void InvokeQueryClientCvarValue2(Edict player, string cvarName, int requestID) => QueryClientCvarValue2?.Invoke(player, cvarName, requestID);
    internal int InvokeEngCheckParm(string pchCmdLineToken, out string ppszValue)
    { 
        if (EngCheckParm != null) 
        { 
            return EngCheckParm.Invoke(pchCmdLineToken, out ppszValue);
        } 
        else 
        {
            ppszValue = string.Empty;
            return 0;
        } 
    }
    #endregion

    #region Null Checker
    internal bool IsPrecacheModelNull => PrecacheModel == null;
    internal bool IsPrecacheSoundNull => PrecacheSound == null;
    internal bool IsSetModelNull => SetModel == null;
    internal bool IsModelIndexNull => ModelIndex == null;
    internal bool IsModelFramesNull => ModelFrames == null;
    internal bool IsSetSizeNull => SetSize == null;
    internal bool IsChangeLevelNull => ChangeLevel == null;
    internal bool IsGetSpawnParmsNull => GetSpawnParms == null;
    internal bool IsSaveSpawnParmsNull => SaveSpawnParms == null;
    internal bool IsVecToYawNull => VecToYaw == null;
    internal bool IsVecToAnglesNull => VecToAngles == null;
    internal bool IsMoveToOriginNull => MoveToOrigin == null;
    internal bool IsChangeYawNull => ChangeYaw == null;
    internal bool IsChangePitchNull => ChangePitch == null;
    internal bool IsFindEntityByStringNull => FindEntityByString == null;
    internal bool IsGetEntityIllumNull => GetEntityIllum == null;
    internal bool IsFindEntityInSphereNull => FindEntityInSphere == null;
    internal bool IsFindClientInPVSNull => FindClientInPVS == null;
    internal bool IsEntitiesInPVSNull => EntitiesInPVS == null;
    internal bool IsMakeVectorsNull => MakeVectors == null;
    internal bool IsAngleVectorsNull => AngleVectors == null;
    internal bool IsCreateEntityNull => CreateEntity == null;
    internal bool IsRemoveEntityNull => RemoveEntity == null;
    internal bool IsCreateNamedEntityNull => CreateNamedEntity == null;
    internal bool IsMakeStaticNull => MakeStatic == null;
    internal bool IsEntIsOnFloorNull => EntIsOnFloor == null;
    internal bool IsDropToFloorNull => DropToFloor == null;
    internal bool IsWalkMoveNull => WalkMove == null;
    internal bool IsSetOriginNull => SetOrigin == null;
    internal bool IsEmitSoundNull => EmitSound == null;
    internal bool IsEmitAmbientSoundNull => EmitAmbientSound == null;
    internal bool IsTraceLineNull => TraceLine == null;
    internal bool IsTraceTossNull => TraceToss == null;
    internal bool IsTraceMonsterHullNull => TraceMonsterHull == null;
    internal bool IsTraceHullNull => TraceHull == null;
    internal bool IsTraceModelNull => TraceModel == null;
    internal bool IsTraceTextureNull => TraceTexture == null;
    internal bool IsTraceSphereNull => TraceSphere == null;
    internal bool IsGetAimVectorNull => GetAimVector == null;
    internal bool IsServerCommandNull => ServerCommand == null;
    internal bool IsServerExecuteNull => ServerExecute == null;
    internal bool IsClientCommandNull => ClientCommand == null;
    internal bool IsParticleEffectNull => ParticleEffect == null;
    internal bool IsLightStyleNull => LightStyle == null;
    internal bool IsDecalIndexNull => DecalIndex == null;
    internal bool IsPointContentsNull => PointContents == null;
    internal bool IsMessageBeginNull => MessageBegin == null;
    internal bool IsMessageEndNull => MessageEnd == null;
    internal bool IsWriteByteNull => WriteByte == null;
    internal bool IsWriteCharNull => WriteChar == null;
    internal bool IsWriteShortNull => WriteShort == null;
    internal bool IsWriteLongNull => WriteLong == null;
    internal bool IsWriteAngleNull => WriteAngle == null;
    internal bool IsWriteCoordNull => WriteCoord == null;
    internal bool IsWriteStringNull => WriteString == null;
    internal bool IsWriteEntityNull => WriteEntity == null;
    internal bool IsCVarRegisterNull => CVarRegister == null;
    internal bool IsCVarGetFloatNull => CVarGetFloat == null;
    internal bool IsCVarGetStringNull => CVarGetString == null;
    internal bool IsCVarSetFloatNull => CVarSetFloat == null;
    internal bool IsCVarSetStringNull => CVarSetString == null;
    internal bool IsAlertMessageNull => AlertMessage == null;
    internal bool IsEngineFprintfNull => EngineFprintf == null;
    internal bool IsPvAllocEntPrivateDataNull => PvAllocEntPrivateData == null;
    internal bool IsPvEntPrivateDataNull => PvEntPrivateData == null;
    internal bool IsFreeEntPrivateDataNull => FreeEntPrivateData == null;
    internal bool IsSzFromIndexNull => SzFromIndex == null;
    internal bool IsAllocStringNull => AllocString == null;
    internal bool IsGetVarsOfEntNull => GetVarsOfEnt == null;
    internal bool IsPEntityOfEntOffsetNull => PEntityOfEntOffset == null;
    internal bool IsEntOffsetOfPEntityNull => EntOffsetOfPEntity == null;
    internal bool IsIndexOfEdictNull => IndexOfEdict == null;
    internal bool IsPEntityOfEntIndexNull => PEntityOfEntIndex == null;
    internal bool IsFindEntityByVarsNull => FindEntityByVars == null;
    internal bool IsGetModelPtrNull => GetModelPtr == null;
    internal bool IsRegUserMsgNull => RegUserMsg == null;
    internal bool IsAnimationAutomoveNull => AnimationAutomove == null;
    internal bool IsGetBonePositionNull => GetBonePosition == null;
    internal bool IsFunctionFromNameNull => FunctionFromName == null;
    internal bool IsNameForFunctionNull => NameForFunction == null;
    internal bool IsClientPrintfNull => ClientPrintf == null;
    internal bool IsServerPrintNull => ServerPrint == null;
    internal bool IsCmd_ArgsNull => Cmd_Args == null;
    internal bool IsCmd_ArgvNull => Cmd_Argv == null;
    internal bool IsCmd_ArgcNull => Cmd_Argc == null;
    internal bool IsGetAttachmentNull => GetAttachment == null;
    internal bool IsCRC32_InitNull => CRC32_Init == null;
    internal bool IsCRC32_ProcessBufferNull => CRC32_ProcessBuffer == null;
    internal bool IsCRC32_ProcessByteNull => CRC32_ProcessByte == null;
    internal bool IsCRC32_FinalNull => CRC32_Final == null;
    internal bool IsRandomLongNull => RandomLong == null;
    internal bool IsRandomFloatNull => RandomFloat == null;
    internal bool IsSetViewNull => SetView == null;
    internal bool IsTimeNull => Time == null;
    internal bool IsCrosshairAngleNull => CrosshairAngle == null;
    internal bool IsLoadFileForMeNull => LoadFileForMe == null;
    internal bool IsFreeFileNull => FreeFile == null;
    internal bool IsEndSectionNull => EndSection == null;
    internal bool IsCompareFileTimeNull => CompareFileTime == null;
    internal bool IsGetGameDirNull => GetGameDir == null;
    internal bool IsCvar_RegisterVariableNull => Cvar_RegisterVariable == null;
    internal bool IsFadeClientVolumeNull => FadeClientVolume == null;
    internal bool IsSetClientMaxspeedNull => SetClientMaxspeed == null;
    internal bool IsCreateFakeClientNull => CreateFakeClient == null;
    internal bool IsRunPlayerMoveNull => RunPlayerMove == null;
    internal bool IsNumberOfEntitiesNull => NumberOfEntities == null;
    internal bool IsGetInfoKeyBufferNull => GetInfoKeyBuffer == null;
    internal bool IsInfoKeyValueNull => InfoKeyValue == null;
    internal bool IsSetKeyValueNull => SetKeyValue == null;
    internal bool IsSetClientKeyValueNull => SetClientKeyValue == null;
    internal bool IsIsMapValidNull => IsMapValid == null;
    internal bool IsStaticDecalNull => StaticDecal == null;
    internal bool IsPrecacheGenericNull => PrecacheGeneric == null;
    internal bool IsGetPlayerUserIdNull => GetPlayerUserId == null;
    internal bool IsBuildSoundMsgNull => BuildSoundMsg == null;
    internal bool IsIsDedicatedServerNull => IsDedicatedServer == null;
    internal bool IsCVarGetPointerNull => CVarGetPointer == null;
    internal bool IsGetPlayerWONIdNull => GetPlayerWONId == null;
    internal bool IsInfo_RemoveKeyNull => Info_RemoveKey == null;
    internal bool IsGetPhysicsKeyValueNull => GetPhysicsKeyValue == null;
    internal bool IsSetPhysicsKeyValueNull => SetPhysicsKeyValue == null;
    internal bool IsGetPhysicsInfoStringNull => GetPhysicsInfoString == null;
    internal bool IsPrecacheEventNull => PrecacheEvent == null;
    internal bool IsPlaybackEventNull => PlaybackEvent == null;
    internal bool IsSetFatPVSNull => SetFatPVS == null;
    internal bool IsSetFatPASNull => SetFatPAS == null;
    internal bool IsCheckVisibilityNull => CheckVisibility == null;
    internal bool IsDeltaSetFieldNull => DeltaSetField == null;
    internal bool IsDeltaUnsetFieldNull => DeltaUnsetField == null;
    internal bool IsDeltaAddEncoderNull => DeltaAddEncoder == null;
    internal bool IsGetCurrentPlayerNull => GetCurrentPlayer == null;
    internal bool IsCanSkipPlayerNull => CanSkipPlayer == null;
    internal bool IsDeltaFindFieldNull => DeltaFindField == null;
    internal bool IsDeltaSetFieldByIndexNull => DeltaSetFieldByIndex == null;
    internal bool IsDeltaUnsetFieldByIndexNull => DeltaUnsetFieldByIndex == null;
    internal bool IsSetGroupMaskNull => SetGroupMask == null;
    internal bool IsCreateInstancedBaselineNull => CreateInstancedBaseline == null;
    internal bool IsCvar_DirectSetNull => Cvar_DirectSet == null;
    internal bool IsForceUnmodifiedNull => ForceUnmodified == null;
    internal bool IsGetPlayerStatsNull => GetPlayerStats == null;
    internal bool IsAddServerCommandNull => AddServerCommand == null;
    internal bool IsVoice_GetClientListeningNull => Voice_GetClientListening == null;
    internal bool IsVoice_SetClientListeningNull => Voice_SetClientListening == null;
    internal bool IsGetPlayerAuthIdNull => GetPlayerAuthId == null;
    internal bool IsSequenceGetNull => SequenceGet == null;
    internal bool IsSequencePickSentenceNull => SequencePickSentence == null;
    internal bool IsGetFileSizeNull => GetFileSize == null;
    internal bool IsGetApproxWavePlayLenNull => GetApproxWavePlayLen == null;
    internal bool IsIsCareerMatchNull => IsCareerMatch == null;
    internal bool IsGetLocalizedStringLengthNull => GetLocalizedStringLength == null;
    internal bool IsRegisterTutorMessageShownNull => RegisterTutorMessageShown == null;
    internal bool IsGetTimesTutorMessageShownNull => GetTimesTutorMessageShown == null;
    internal bool IsProcessTutorMessageDecayBufferNull => ProcessTutorMessageDecayBuffer == null;
    internal bool IsConstructTutorMessageDecayBufferNull => ConstructTutorMessageDecayBuffer == null;
    internal bool IsResetTutorMessageDecayDataNull => ResetTutorMessageDecayData == null;
    internal bool IsQueryClientCvarValueNull => QueryClientCvarValue == null;
    internal bool IsQueryClientCvarValue2Null => QueryClientCvarValue2 == null;
    internal bool IsEngCheckParmNull => EngCheckParm == null;
    #endregion
}

